//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string Answer { get; set; }
        public int IDTesting { get; set; }
        public int IDTheory { get; set; }
    
        public virtual Testing Testing { get; set; }
        public virtual Theory Theory { get; set; }
    }
}
