//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testing
    {
        public int ID { get; set; }
        public int Estimation { get; set; }
        public int CorrectAnswers { get; set; }
        public System.DateTime Started { get; set; }
        public System.DateTime Ended { get; set; }
        public int IDStudent { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
